PREFIX schema: <http://schema.org/>  
PREFIX adr: <http://kg.artsdata.ca/resource/>  

insert {
  ?place schema:sameAs  ?artsdata_place

}
where {
  ?place a schema:Place ;

  OPTIONAL {
    ?place  schema:name "Fourth Stage" .
    bind(adr:K11-17 as ?artsdata_place)
  }

  OPTIONAL {
    ?place  schema:name "Southam Hall" .
    bind(adr:K11-20 as ?artsdata_place)
  }

  OPTIONAL {
    ?place  schema:name "Canada Room" .
    bind(adr:K11-35 as ?artsdata_place)
  }

  OPTIONAL {
    ?place  schema:name "Babs Asper Theatre" .
    bind(adr:K11-16 as ?artsdata_place)
  }

  OPTIONAL {
    ?place  schema:name "Studio Azrieli" .
    bind(adr:K11-15 as ?artsdata_place)
  }

  OPTIONAL {
    ?place  schema:name "Peter A. Herrndorf Place" .
    bind(<http://www.wikidata.org/entity/Q111730745> as ?artsdata_place)
  }
}