delete {
   ?s schema:eventStatus ?eventStatus .
}
insert {
   ?s ?p <http://schema.org/EventScheduled>
}
where {
  ?s schema:eventStatus ?eventStatus .
  filter (strends(?eventStatus, "EventScheduled")) .
 
}
