PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>

DELETE {
  ?s ?p ?o .
  ?s <schema:organizer> ?o .
}
WHERE {
  {
    ?s ?p ?o .
    ?s a schema:Organization .
    ?s schema:name "" .
  }
  UNION
  {
    ?s ?p ?o .
    ?o a schema:Organization .
    FILTER NOT EXISTS {
      ?p schema:name "" .
    }
  }
}
