name: Fetch NAC entities - v2

on:
  workflow_dispatch:
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v4
        with:
          mode: "fetch-test"
          artifact: "nac-xpath-test"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "output/entities-v2.jsonld"
          page-url: "https://nac-cna.ca/site/sitemap-ssl"
          entity-identifier: "//loc[contains(text(), '/event/')"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: "${{ secrets.CLOUDFLARE_PRIVATE_KEY }}"
